"""
AI Content Workflow Tool for E-commerce
FastAPI backend — generates marketing content from product details.

Content source (checked once at startup):
  • If ANTHROPIC_API_KEY is set  → content is generated by Claude (claude-opus-4-6)
  • If ANTHROPIC_API_KEY is missing → falls back to the built-in mock generator

──────────────────────────────────────────────────────────────────────────────
SETUP: Using the Claude API
──────────────────────────────────────────────────────────────────────────────
1. Get your API key at https://console.anthropic.com/
2. Set the environment variable before starting the server:

   # macOS / Linux
   export ANTHROPIC_API_KEY="sk-ant-..."

   # Windows (Command Prompt)
   set ANTHROPIC_API_KEY=sk-ant-...

   # Windows (PowerShell)
   $env:ANTHROPIC_API_KEY="sk-ant-..."

   # Or create a .env file and load it with `python-dotenv` (optional)

3. Start the server as normal:
   uvicorn api:app --reload

The app will print "Claude API enabled" or "Mock generator active" on startup.
──────────────────────────────────────────────────────────────────────────────
"""

import os
import json
import random

import anthropic
from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel

# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------

app = FastAPI(title="AI Content Workflow Tool")

app.mount("/static", StaticFiles(directory="static"), name="static")

# ---------------------------------------------------------------------------
# Claude client — created once at startup if the API key is present.
# The anthropic library reads ANTHROPIC_API_KEY automatically.
# ---------------------------------------------------------------------------

_api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()

if _api_key:
    _claude = anthropic.Anthropic(api_key=_api_key)
    print("[OK] Claude API enabled  (model: claude-opus-4-6)")
else:
    _claude = None
    print("[INFO] ANTHROPIC_API_KEY not set -- Mock generator active")


# ---------------------------------------------------------------------------
# Data model for the incoming request
# ---------------------------------------------------------------------------

class ProductInput(BaseModel):
    product_name: str
    category: str
    features: str
    audience: str
    tone: str
    platform: str


# ---------------------------------------------------------------------------
# Claude-powered content generation
# ---------------------------------------------------------------------------

# System prompt: establishes a specific copywriter persona with clear
# writing principles rather than a generic "expert copywriter" instruction.
_SYSTEM_PROMPT = """\
You are a senior copywriter with 15 years writing for beauty brands across
DTC, social, and retail channels. Your work has appeared for brands like
Glossier, Fenty Beauty, and Rhode.

Your copy is specific and human. You never lean on tired beauty clichés like
"unleash your glow", "because you're worth it", or "elevate your routine".
You earn attention with real product knowledge, an honest voice, and language
that sounds like it was written for one particular person — not a demographic.

You read brand tone as a full personality, not a label:
  playful    -> witty, conversational, a little self-aware
  luxurious  -> confident and precise, no need to shout
  empowering -> direct, inclusive, action-forward
  minimal    -> spare and honest, trusts the product to speak
  edgy       -> provocative but considered, never try-hard

Return ONLY valid JSON. No markdown fences. No extra keys. No commentary."""


def _build_user_prompt(name: str, category: str, features: str,
                        audience: str, tone: str, platform: str) -> str:
    """
    Build the user message sent to Claude.
    Each field gets specific rules to push output away from generic templates
    and toward copy that sounds like a real brand voice.
    """
    return f"""\
Write marketing copy for the product below. Make it feel like a real brand — \
not a fill-in-the-blank template.

Product  : {name}
Category : {category}
Features : {features}
Audience : {audience}
Tone     : {tone}
Platform : {platform}

Return a JSON object with exactly these five keys:

{{
  "description"   : "...",
  "headlines"     : ["...", "...", "..."],
  "tiktok_script" : "...",
  "cta"           : "...",
  "hashtags"      : ["#...", "#...", "#...", "#...", "#..."]
}}

Rules per field
---------------

description (60-90 words):
- Lead with the product's single most compelling quality, not its name
- Write as if recommending it to a friend who would genuinely want it
- Do NOT use: "introducing", "elevate your routine", "your best skin yet",
  "game-changer", or any variation of "glow up"

headlines (exactly 3, under 8 words each):
- Give each headline a distinct angle:
    1. A direct, specific benefit
    2. A statement of identity that the target audience owns
    3. A question or provocation that creates curiosity
- Avoid: "the {category} you've been waiting for", "results you'll love",
  "meet your new favourite"

tiktok_script (three labelled sections):
- [Hook]  — one sentence that stops the scroll; use a POV, confession,
            or a bold claim. Make it specific to the product, not generic.
- [Value] — one to two sentences using actual features to explain why it works.
            Sound like a friend, not an ad.
- [CTA]   — one direct sentence suited to {platform}

cta (one sentence only):
- Platform-appropriate for {platform}
- Lead with an action verb
- Tone must match: {tone}
- Do not repeat the headline or tiktok_script CTA word-for-word

hashtags (exactly 5):
- Mix: 1 product/brand tag, 2 category tags, 2 community or trend tags
- camelCase or lowercase only
- All five must be genuinely searchable — no invented phrases"""


def generate_with_claude(name: str, category: str, features: str,
                          audience: str, tone: str, platform: str) -> dict:
    """
    Call Claude to generate marketing content.
    Uses a direct messages.create() call — output is short (~500 tokens)
    so streaming is unnecessary here.
    Returns a dict matching the standard response shape.
    Raises HTTPException on API or parse errors so FastAPI returns a clean error.
    """
    try:
        response = _claude.messages.create(
            model="claude-opus-4-6",
            max_tokens=1200,
            system=_SYSTEM_PROMPT,
            messages=[{
                "role": "user",
                "content": _build_user_prompt(
                    name, category, features, audience, tone, platform
                ),
            }],
        )

        raw_text = response.content[0].text
        data = json.loads(raw_text)

        # Confirm all five keys are present before returning
        required = {"description", "headlines", "tiktok_script", "cta", "hashtags"}
        missing = required - data.keys()
        if missing:
            raise ValueError(f"Claude response is missing keys: {missing}")

        return data

    except anthropic.AuthenticationError:
        raise HTTPException(
            status_code=502,
            detail="Invalid ANTHROPIC_API_KEY. Check your key and restart the server.",
        )
    except anthropic.RateLimitError:
        raise HTTPException(
            status_code=429,
            detail="Claude API rate limit reached. Please wait a moment and try again.",
        )
    except anthropic.APIStatusError as exc:
        raise HTTPException(
            status_code=502,
            detail=f"Claude API error ({exc.status_code}): {exc.message}",
        )
    except (json.JSONDecodeError, ValueError) as exc:
        raise HTTPException(
            status_code=502,
            detail=f"Could not parse Claude's response: {exc}",
        )


# ---------------------------------------------------------------------------
# Mock content generation (used when ANTHROPIC_API_KEY is not set)
# ---------------------------------------------------------------------------

TONE_ADJECTIVES: dict[str, list[str]] = {
    "playful":    ["fun", "vibrant", "irresistible", "cheeky", "feel-good"],
    "luxurious":  ["indulgent", "refined", "opulent", "sophisticated", "premium"],
    "empowering": ["bold", "confident", "unstoppable", "fearless", "powerful"],
    "minimal":    ["clean", "effortless", "pure", "simple", "understated"],
    "edgy":       ["fierce", "unapologetic", "daring", "raw", "intense"],
}
DEFAULT_ADJECTIVES = ["amazing", "innovative", "must-have", "standout", "exceptional"]


def _adj(tone: str) -> str:
    pool = TONE_ADJECTIVES.get(tone.lower(), DEFAULT_ADJECTIVES)
    return random.choice(pool)


def _mock_description(name, category, features, audience, tone):
    feature_list = [f.strip() for f in features.split(",")]
    top = feature_list[:3] if len(feature_list) >= 3 else feature_list
    return (
        f"Introducing {name} — the {_adj(tone)} addition to your {category.lower()} routine. "
        f"Crafted for {audience.lower()}, this {_adj(tone)} formula delivers "
        f"{', '.join(top).lower()}. "
        f"Whether you're starting fresh or elevating your everyday look, {name} makes it "
        f"{_adj(tone)} and effortless. "
        f"Because great {category.lower()} should feel as good as it looks. "
        f"Trusted by beauty lovers who refuse to settle for less."
    )


def _mock_headlines(name, category, tone):
    templates = [
        f"Your New {_adj(tone).capitalize()} {category} Essential",
        f"{name}: {_adj(tone).capitalize()} Results, Every Time",
        f"Meet the {category} Drop You've Been Waiting For",
        f"The {_adj(tone).capitalize()} Way to Do {category}",
        f"{name} — Because You Deserve {_adj(tone).capitalize()}",
        f"Level Up Your {category} with {name}",
    ]
    return random.sample(templates, 3)


def _mock_tiktok_script(name, features, audience, tone):
    feature_list = [f.strip() for f in features.split(",")]
    highlight = feature_list[0] if feature_list else "incredible results"
    hook  = random.choice([
        f"POV: you finally found a {name.lower()} that actually works 👀",
        f"Tell me why I waited so long to try {name}...",
        f"This is your sign to upgrade your routine with {name} ✨",
        f"No cap — {name} just changed my entire routine 🙌",
    ])
    value = random.choice([
        f"It's {_adj(tone)}, it's got {highlight.lower()}, "
        f"and {audience.lower()} are absolutely obsessed.",
        f"Packed with {highlight.lower()} — perfect for {audience.lower()} "
        f"who want {_adj(tone)} results without the hassle.",
    ])
    cta = random.choice([
        "Link in bio — don't sleep on this drop!",
        "Tap the link in bio before it sells out 🔥",
        "Grab yours now — link in bio!",
    ])
    return f"[Hook] {hook}\n\n[Value] {value}\n\n[CTA] {cta}"


def _mock_cta(name, platform, tone):
    ctas = {
        "TikTok":    f"Tap the link in bio and shop {name} today — your routine deserves it! 🛍️",
        "Instagram": f"Shop {name} now via the link in bio. {_adj(tone).capitalize()} vibes only ✨",
        "Shopify":   f"Add {name} to your cart — because {_adj(tone)} is always in season.",
        "Amazon":    f"Order {name} on Amazon today and get it at your door fast. Shop now ➡️",
    }
    return ctas.get(platform, f"Shop {name} now and experience {_adj(tone)} results today!")


def _mock_hashtags(name, category, platform):
    slug = name.replace(" ", "").lower()
    cat  = category.replace(" ", "").lower()
    pool = [
        f"#{slug}", f"#{cat}", f"#{cat}routine", f"#{cat}lover",
        f"#new{cat}", f"#beautyessentials", f"#skincarecheck",
        f"#makeupoftheday", f"#beautytips", f"#{platform.lower()}beauty",
        f"#beautycommunity", f"#glowup",
    ]
    return random.sample(pool, 5)


def generate_with_mock(name, category, features, audience, tone, platform) -> dict:
    """Generate content using Python templates (no API key required)."""
    return {
        "description":   _mock_description(name, category, features, audience, tone),
        "headlines":     _mock_headlines(name, category, tone),
        "tiktok_script": _mock_tiktok_script(name, features, audience, tone),
        "cta":           _mock_cta(name, platform, tone),
        "hashtags":      _mock_hashtags(name, category, platform),
    }


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/")
def serve_index():
    """Serve the single-page frontend."""
    return FileResponse("static/index.html")


@app.post("/generate")
def generate_content(product: ProductInput):
    """
    Accept product details and return marketing content.
    Uses Claude API when ANTHROPIC_API_KEY is set, otherwise uses mock generator.
    """
    name     = product.product_name.strip()
    category = product.category.strip()
    features = product.features.strip()
    audience = product.audience.strip()
    tone     = product.tone.strip()
    platform = product.platform.strip()

    if _claude:
        # Real AI-generated content
        content = generate_with_claude(name, category, features, audience, tone, platform)
    else:
        # Fallback: template-based mock content
        content = generate_with_mock(name, category, features, audience, tone, platform)

    return JSONResponse(content)
